[project]
name = "api"
version = "0.1.0"
description = "General backend for jobs.devinl.im"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "psycopg2-binary>=2.9.10",
    "sqlmodel>=0.0.24",
]
